### ISSUE TITLE
module 'OpenSSL.crypto' has no attribute 'PKCS12'

### ISSUE THREAD

**Issue by h3retic** [ShutdownRepo/pywhisker#17]
```
pywhisker.py -d example.com -u computer\$ -H 2dfcebbe9f5f4cb3bf98032887be37b6 --target User -a add
[*] Searching for the target account
[*] Target user found: CN=User,CN=Users,DC=example,DC=com
[*] Generating certificate
[*] Certificate generated
[*] Generating KeyCredential
[*] KeyCredential generated with DeviceID: 57ec5c73-45e5-b734-b029-8432954b1352
[*] Updating the msDS-KeyCredentialLink attribute of User
[+] Updated the msDS-KeyCredentialLink attribute of the target object
[!] module 'OpenSSL.crypto' has no attribute 'PKCS12'
```

**Comment by ErickAbadSantana** [comment]
Good afternoon, for all users who are experiencing this problem, Investigations will lead us to the conclusion that the `**OpenSSL.crypto**` library has made an update that is not compatible with the `Source Code` of the tool.

However, to solve this problem temporarily, until the creators of the tool implement a solution for the Source Code, we can use a lower version of the library, this can be done by deleting the existing version, and then modifying the requirements.txt file, so that it looks like this: 

**impacket
pyOpenSSL==24.0.0
cryptography
six
pyasn1
ldap3
ldapdomaindump
rich
setuptools
dsinternals**

Afterwards, you just have to execute the command: **pip3 install -r requirements.txt** .

When you run the command again, the problem should be solved.

**Comment by ShutdownRepo** [comment]
Thank you for raising the issue
Impacket seems to have fixed it upstream, we should be good to go now https://github.com/fortra/impacket/issues/1716

**Comment by ErickAbadSantana** [comment]
To order, you are welcome.
________________________________
